name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make checksum executable
        run: chmod +x ./checksum.sh

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/cache@v1
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug --scan --stacktrace

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.10.0-RC1
        with:
          args: --fail-fast --config .github/detekt.yml
